apiVersion: v1
kind: ReplicationController
metadata:
  labels: {name: jenkins}
  name: jenkins
spec:
  replicas: 1
  selector:
    app: jenkins
  template:
    metadata:
      labels: {app: jenkins}
    spec:
      containers:
      - image: jenkins_root:v0.0
        name: jenkins-root
        ports:
        - {containerPort: 50000, name: port-1}
        - {containerPort: 8080, name: port-2}
        volumeMounts:
        - {mountPath: /var/jenkins_home, name: jenkins-persistent-storage}
      imagePullSecrets:
      - name: sdnsecret
      dnsPolicy: Default
      volumes:
      - hostPath: {path: /nobackup/volume/jenkins}
        name: jenkins-persistent-storage