apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 6379
  selector:
    name: redis